### ISSUE TITLE
Enumerate RPC calls

### ISSUE THREAD

**Issue by gdassori** [orange-org/orange#6]
Hi, it would be helpful to me to see RPC calls explicitly enumerated, since I'd like to see if it is feasable to enhance spruned's RPC interface (https://github.com/gdassori/spruned) and use orange as a frontend for it.

**Comment by msafi** [comment]
Hi @gdassori,

Are you saying you want to swap `bitcoind` with `spruned`? As long as `spruned` RPC requests and responses are compatible with `bitcoind`, that should work. Currently Orange uses the following [RPC requests](https://github.com/orange-org/orange/blob/6cd37f2ca37c005c2777863d2342735233c9840d/src/typings/bitcoindRpcRequests.ts) and expects these [RPC responses](https://github.com/orange-org/orange/blob/6cd37f2ca37c005c2777863d2342735233c9840d/src/typings/bitcoindRpcResponses.ts).

But since spruned is targeting lightweight systems, I don't think you want to use Electron right?

**Comment by gdassori** [comment]
Yes, to replace bitcoind in some environments, not necessarily just the lightweight ones, is spruned's purpose. Also, to test bitcoind backed applications using spruned is something I occasionally do cause it may highlight regressions, issues, race conditions.. whatever. 

Regarding what you do at the moment with Orange, looks like on spruned's side the only missing API is `setnetworkactive`. I think I may work on that. 

Thank you, I hope you'll keep working on this!

**Comment by msafi** [comment]
Great, thanks! Let me know how it goes with Orange + spruned when you get to it!
